### ISSUE TITLE
新建用户实体

### ISSUE THREAD

**Issue by chuhang123** [yunzhiclub/WaterPurifier#11]

**Comment by chuhang123** [comment]
doing

**Comment by chuhang123** [comment]
done

**Comment by teacherpan** [comment]
doing

**Comment by teacherpan** [comment]
用户实体User 指使用这个系统的用户。客户表Customer，指饮水机用户。

**Comment by chuhang123** [comment]
![image](https://cloud.githubusercontent.com/assets/16712674/26815845/41b4290a-4ac1-11e7-95af-4d7163e2ab4a.png)
