### ISSUE TITLE
修改ER图，增加 用户表

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/WaterPurifier#22]

**Comment by teacherpan** [comment]
@chuhang123  在根目录中，新建document文件夹，将er图，上传到document文件夹中。
![image](https://cloud.githubusercontent.com/assets/12424383/26808120/4d5c875e-4a8d-11e7-895f-17e189b1f388.png)

**Comment by chuhang123** [comment]
![image](https://cloud.githubusercontent.com/assets/16712674/26819783/00e17c4a-4ad3-11e7-84fd-d0e541cbf1b7.png)
