### ISSUE TITLE
原型：绑定、解绑饮水机

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/WaterPurifier#4]
将原型，直接截图到评论中。

**Comment by chuhang123** [comment]
![image](https://cloud.githubusercontent.com/assets/16712674/26772093/fba7f782-49f5-11e7-8729-01c99174a3d7.png)

**Comment by teacherpan** [comment]
![image](https://cloud.githubusercontent.com/assets/12424383/26772453/11b52b92-49f8-11e7-8ab8-fbeb3b03da7c.png)
上面不要。直接给出净水器编号。如果为重新绑定，则用原编号自动填充。

**Comment by chuhang123** [comment]
好的

**Comment by teacherpan** [comment]
该原型完成后，将所有原型的代码进行pull

**Comment by chuhang123** [comment]
![_049](https://cloud.githubusercontent.com/assets/16712674/26772945/29517898-49fb-11e7-9d1b-0f9dbfb9cb4a.png)

**Comment by teacherpan** [comment]
可以。将代码提交上来吧。

**Comment by chuhang123** [comment]
好的
