### ISSUE TITLE
原型：查看饮水机状态：滤芯状态。过滤前后水质。

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/WaterPurifier#6]

**Comment by chuhang123** [comment]
![Uploading image.png…]()

**Comment by chuhang123** [comment]
![_047](https://cloud.githubusercontent.com/assets/16712674/26772402/c709e7e0-49f7-11e7-8b39-1f479f5c17e9.png)

**Comment by teacherpan** [comment]
TODO：饮水机编号，或是选择饮水机。
