### ISSUE TITLE
原型：充值。选择饮水机，输入金额，自动计算充值水量。

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/WaterPurifier#7]

**Comment by chuhang123** [comment]
![_048](https://cloud.githubusercontent.com/assets/16712674/26772422/e01f191c-49f7-11e7-9a6d-de100f7dbede.png)

**Comment by teacherpan** [comment]
TODO：选择饮水机

**Comment by chuhang123** [comment]
![image](https://cloud.githubusercontent.com/assets/16712674/26773237/ff1e7358-49fc-11e7-948a-5d9364615cb7.png)
